// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CssController from "./css_controller"
application.register("css", CssController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import SwalController from "./swal_controller"
application.register("swal", SwalController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
